rrpak: Be a bit more verbose.

diff --git a/rrpak b/rrpak
--- a/rrpak
+++ b/rrpak
@@ -214,8 +214,11 @@ normalize_packages () {
   done
   local tmp
   tmp=$(printf '%s\n' "${packages[@]}" | sort -u)
+  if [[ "$tmp" == "" ]]; then
+    echo >&2 "rrpak: error: Package list is empty"
+    exit 1
+  fi
   mapfile -t packages <<< "$tmp"
-  if [[ "$tmp" == "" ]]; then packages=(); fi
 }
 
 do_build () {
@@ -228,6 +231,8 @@ do_build () {
     echo >&2 "rrpak: error: '$destination' is not empty"
     exit 1
   done
+
+  echo >&2 "rrpak: Installing ${packages[*]} to $destination..."
 
   mkdir -p "$destination"
   touch "$destination/rc"
@@ -251,6 +256,8 @@ do_build () {
     if ! [[ -e misc/micromambabin/micromamba ]]; then
       put_micromamba_in_misc
     fi
+
+    echo >&2 "rrpak: Installing ${condapackages[*]} to $destination/menv using micromamba"
 
     unset "${!CONDA@}"
     unset "${!MAMBA@}"
@@ -334,6 +341,8 @@ do_build () {
   done
 
   cd "$oldcwd"
+
+  echo >&2 "rrpak: Done with installing ${packages[*]}."
 }
 
 (( $# == 0 )) && usage 0
@@ -497,11 +506,9 @@ case "$cmd" in
     if [[ "$destination" == "" ]]; then
       destination=$(mktemp -d -p "$rrpak_local_cache_path" env.XXXXXXXXXX.rrpak)
 
-      echo >&2 "rrpak: Installing ${packages[*]} to $destination..."
       do_build
       touch "$destination/created" "$destination/runlock"
       ln -sfT "${destination##*/}" "$rrpak_local_cache_path/$symlink"
-      echo >&2 "rrpak: Done."
     fi
 
     touch "$destination/used"
